import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Main from './FormExports/MainPages';
/*Main, primary file of the project*/
const Home = () => (
  <div className={styles.container}>
      <Head>
        <title>Formulario</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"></link>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin></link>
        <link href="https://fonts.googleapis.com/css2?family=Concert+One&display=swap" rel="stylesheet"></link>
      </Head>
      <main className={styles.main}>
          <Main />
      </main>
      
  </div>
)

export default Home;